// <auto-generated />
using System;
using System.Collections.Generic;
using DatingApp.ProfileService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatingApp.ProfileService.Infrastructure.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20251127084408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatingApp.ProfileService.Core.Domain.Entities.MemberProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("completion_percentage");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExposureLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exposure_level");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_member_profiles_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_member_profiles_deleted_at");

                    b.HasIndex("IsComplete")
                        .HasDatabaseName("ix_member_profiles_is_complete");

                    b.ToTable("member_profiles", (string)null);
                });

            modelBuilder.Entity("DatingApp.ProfileService.Core.Domain.Entities.MemberProfile", b =>
                {
                    b.OwnsOne("DatingApp.ProfileService.Core.Domain.ValueObjects.Lifestyle", "Lifestyle", b1 =>
                        {
                            b1.Property<Guid>("MemberProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DietType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("lifestyle_diet_type");

                            b1.Property<string>("DrinkingFrequency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("lifestyle_drinking_frequency");

                            b1.Property<string>("ExerciseFrequency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("lifestyle_exercise_frequency");

                            b1.Property<bool>("HasPets")
                                .HasColumnType("boolean")
                                .HasColumnName("lifestyle_has_pets");

                            b1.Property<string>("SmokingStatus")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("lifestyle_smoking_status");

                            b1.Property<string>("WantsChildren")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("lifestyle_wants_children");

                            b1.HasKey("MemberProfileUserId");

                            b1.ToTable("member_profiles");

                            b1.WithOwner()
                                .HasForeignKey("MemberProfileUserId");
                        });

                    b.OwnsOne("DatingApp.ProfileService.Core.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("MemberProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("longitude");

                            b1.HasKey("MemberProfileUserId");

                            b1.ToTable("member_profiles");

                            b1.WithOwner()
                                .HasForeignKey("MemberProfileUserId");
                        });

                    b.OwnsOne("DatingApp.ProfileService.Core.Domain.ValueObjects.PersonalityProfile", "Personality", b1 =>
                        {
                            b1.Property<Guid>("MemberProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AboutMe")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("personality_about_me");

                            b1.Property<int>("Agreeableness")
                                .HasColumnType("integer")
                                .HasColumnName("personality_agreeableness");

                            b1.Property<int>("Conscientiousness")
                                .HasColumnType("integer")
                                .HasColumnName("personality_conscientiousness");

                            b1.Property<int>("Extraversion")
                                .HasColumnType("integer")
                                .HasColumnName("personality_extraversion");

                            b1.Property<string>("LifePhilosophy")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("personality_life_philosophy");

                            b1.Property<int>("Neuroticism")
                                .HasColumnType("integer")
                                .HasColumnName("personality_neuroticism");

                            b1.Property<int>("Openness")
                                .HasColumnType("integer")
                                .HasColumnName("personality_openness");

                            b1.HasKey("MemberProfileUserId");

                            b1.ToTable("member_profiles");

                            b1.WithOwner()
                                .HasForeignKey("MemberProfileUserId");
                        });

                    b.OwnsOne("DatingApp.ProfileService.Core.Domain.ValueObjects.PreferenceSet", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("MemberProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GenderPreference")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("preferences_gender");

                            b1.Property<int>("MaxDistanceKm")
                                .HasColumnType("integer")
                                .HasColumnName("preferences_max_distance_km");

                            b1.Property<List<string>>("PreferredLanguages")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("preferences_languages");

                            b1.HasKey("MemberProfileUserId");

                            b1.ToTable("member_profiles");

                            b1.WithOwner()
                                .HasForeignKey("MemberProfileUserId");

                            b1.OwnsOne("DatingApp.ProfileService.Core.Domain.ValueObjects.AgeRange", "PreferredAgeRange", b2 =>
                                {
                                    b2.Property<Guid>("PreferenceSetMemberProfileUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Max")
                                        .HasColumnType("integer")
                                        .HasColumnName("preferences_age_max");

                                    b2.Property<int>("Min")
                                        .HasColumnType("integer")
                                        .HasColumnName("preferences_age_min");

                                    b2.HasKey("PreferenceSetMemberProfileUserId");

                                    b2.ToTable("member_profiles");

                                    b2.WithOwner()
                                        .HasForeignKey("PreferenceSetMemberProfileUserId");
                                });

                            b1.Navigation("PreferredAgeRange")
                                .IsRequired();
                        });

                    b.OwnsOne("DatingApp.ProfileService.Core.Domain.ValueObjects.Values", "Values", b1 =>
                        {
                            b1.Property<Guid>("MemberProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Adventure")
                                .HasColumnType("integer")
                                .HasColumnName("values_adventure");

                            b1.Property<int>("CareerAmbition")
                                .HasColumnType("integer")
                                .HasColumnName("values_career_ambition");

                            b1.Property<int>("Environmentalism")
                                .HasColumnType("integer")
                                .HasColumnName("values_environmentalism");

                            b1.Property<int>("FamilyOrientation")
                                .HasColumnType("integer")
                                .HasColumnName("values_family_orientation");

                            b1.Property<int>("FinancialSecurity")
                                .HasColumnType("integer")
                                .HasColumnName("values_financial_security");

                            b1.Property<int>("IntellectualCuriosity")
                                .HasColumnType("integer")
                                .HasColumnName("values_intellectual_curiosity");

                            b1.Property<int>("SocialJustice")
                                .HasColumnType("integer")
                                .HasColumnName("values_social_justice");

                            b1.Property<int>("Spirituality")
                                .HasColumnType("integer")
                                .HasColumnName("values_spirituality");

                            b1.HasKey("MemberProfileUserId");

                            b1.ToTable("member_profiles");

                            b1.WithOwner()
                                .HasForeignKey("MemberProfileUserId");
                        });

                    b.Navigation("Lifestyle");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Personality");

                    b.Navigation("Preferences");

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
